Feature/update link in documentation
dunglas/mercure pull request #376
Opened 2020-09-18 08:47 UTC by maxime-urbanski

* `fix`: Fix path for CONTRIBUTING.md

2020-09-18 08:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dunglas/mercure?pullRequest=376) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dunglas/mercure?pullRequest=376) before we can accept your contribution.<br/><hr/>**maxiloud** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dunglas/mercure?pullRequest=376) it.</sub>

2020-09-18 09:50 UTC, dunglas requested changes
Or the link will break on the website.

2020-09-18 09:50 UTC, dunglas commented on docs/hub/install.md
> +To compile the development version and register the demo page, see [https://github.com/dunglas/mercure/blob/master/CONTRIBUTING.md](../../CONTRIBUTING.md#hub).
```suggestion
To compile the development version and register the demo page, see [https://github.com/dunglas/mercure/blob/master/CONTRIBUTING.md](https://github.com/dunglas/mercure/blob/master/CONTRIBUTING.md).
```

2020-09-18 11:38 UTC, maxime-urbanski commented on docs/hub/install.md
> +To compile the development version and register the demo page, see [https://github.com/dunglas/mercure/blob/master/CONTRIBUTING.md](../../CONTRIBUTING.md#hub).
Ok, i changed the link.

2020-09-26 06:42 UTC, merged

2020-09-26 06:42 UTC, dunglas commented
Thanks @maxime-urbanski