Authorization: add code examples
dunglas/mercure pull request #415
Opened 2020-12-09 11:33 UTC by alexislefebvre

I took examples from Symfony's documentation: https://symfony.com/doc/4.4/mercure.html#authorization

2020-12-15 00:19 UTC, dunglas commented
Hi, thanks for your contribution. In my opinion this shouldn't be in the spec itself. The spec shouldn't reference non-standard features such as passing custom headers with `EventSource` and don't have to be exhaustive regarding other use cases covered by other specs such as EventSource (implementers must refer to the linked spec instead).

Would you mind to move these examples in [the FAQ](https://github.com/dunglas/mercure/tree/main/docs/spec/faq.md) instead?

2021-03-27 12:49 UTC, alexislefebvre commented
@dunglas hi, I moved the text to the FAQ.

2021-03-28 10:14 UTC, dunglas requested changes
We are almost there, thanks!

2021-03-28 10:14 UTC, dunglas commented on docs/spec/faq.md
> +If the client is not a web browser, cookies can't be used.
This should be removed, most popular HTTP clients including `curl` also support cookies.

2021-03-28 10:14 UTC, dunglas commented on docs/spec/faq.md
> +In order to achieve that, use a [polyfill](https://github.com/Yaffle/EventSource):
Actually the polyfill is only useful for very old browsers and for cross-domain authorization.

2021-04-19 20:59 UTC, dunglas approved these changes

2021-04-19 20:59 UTC, merged