docs: fix in Traefik Hub example - curl is not installed
dunglas/mercure pull request #954
Opened 2024-09-23 11:31 UTC by gander

docs: fix in Traefik Hub example - curl is not installed in the docker image

2024-09-23 11:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dunglas/mercure?pullRequest=954) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dunglas/mercure?pullRequest=954) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dunglas/mercure?pullRequest=954) it.</sub>

2024-09-23 11:48 UTC, dunglas requested changes

2024-09-23 11:48 UTC, dunglas commented on docs/hub/traefik.md
> +      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/healthz"]
```suggestion
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/healthz"]
```

2024-09-23 13:53 UTC, dunglas commented
Perfect. Can you sign the CLA, please?

2024-09-24 09:54 UTC, gander commented
@dunglas accepted

2024-09-27 09:15 UTC, merged

2024-09-27 09:15 UTC, dunglas commented
Thanks!